// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PumpRoomAutomationBackend.Data;
using PumpRoomAutomationBackend.Models.Enums;

#nullable disable

namespace PumpRoomAutomationBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251210063643_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.AlarmConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlarmCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("alarm_category");

                    b.Property<string>("AlarmCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("alarm_code");

                    b.Property<string>("AlarmMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alarm_message");

                    b.Property<string>("AlarmName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alarm_name");

                    b.Property<bool>("AutoClear")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_clear");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("RequireConfirmation")
                        .HasColumnType("boolean")
                        .HasColumnName("require_confirmation");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<int?>("SiteId")
                        .HasColumnType("integer")
                        .HasColumnName("site_id");

                    b.Property<string>("SolutionGuide")
                        .HasColumnType("text")
                        .HasColumnName("solution_guide");

                    b.Property<int?>("TriggerBit")
                        .HasColumnType("integer")
                        .HasColumnName("trigger_bit");

                    b.Property<string>("TriggerVariable")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("trigger_variable");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("AlarmCategory");

                    b.HasIndex("AlarmCode")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("Severity");

                    b.HasIndex("SiteId");

                    b.ToTable("alarm_configs");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.AlarmRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("acknowledged_by");

                    b.Property<DateTime?>("AcknowledgedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_time");

                    b.Property<string>("AlarmDescription")
                        .HasColumnType("text")
                        .HasColumnName("alarm_description");

                    b.Property<DateTime?>("AlarmEndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alarm_end_time");

                    b.Property<string>("AlarmName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("alarm_name");

                    b.Property<DateTime>("AlarmStartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alarm_start_time");

                    b.Property<string>("AlarmValue")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("alarm_value");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CurrentValue")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("current_value");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("node_id");

                    b.Property<string>("NodeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("node_name");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<AlarmSeverity>("Severity")
                        .HasColumnType("alarmseverity")
                        .HasColumnName("severity");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer")
                        .HasColumnName("site_id");

                    b.Property<AlarmStatus>("Status")
                        .HasColumnType("alarmstatus")
                        .HasColumnName("status");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("alarm_records");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.Current", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DataQuality")
                        .HasColumnType("integer")
                        .HasColumnName("data_quality");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(10, 3)")
                        .HasColumnName("current");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "Timestamp")
                        .IsUnique()
                        .HasDatabaseName("idx_currents_site_time");

                    b.ToTable("currents");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.DownstreamWaterLevel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<short>("DataQuality")
                        .HasColumnType("smallint")
                        .HasColumnName("data_quality");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<decimal>("WaterLevel")
                        .HasColumnType("numeric(10, 3)")
                        .HasColumnName("water_level");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "Timestamp")
                        .IsUnique()
                        .HasDatabaseName("idx_downstream_levels_site_time");

                    b.ToTable("downstream_water_levels");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.ExternalHumidity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DataQuality")
                        .HasColumnType("integer")
                        .HasColumnName("data_quality");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(10, 3)")
                        .HasColumnName("externalhumidity");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "Timestamp")
                        .IsUnique()
                        .HasDatabaseName("idx_externalhumiditys_site_time");

                    b.ToTable("externalhumiditys");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.ExternalTemp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DataQuality")
                        .HasColumnType("integer")
                        .HasColumnName("data_quality");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(10, 3)")
                        .HasColumnName("externaltemp");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "Timestamp")
                        .IsUnique()
                        .HasDatabaseName("idx_externaltemps_site_time");

                    b.ToTable("externaltemps");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.FlowVelocity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<short>("DataQuality")
                        .HasColumnType("smallint")
                        .HasColumnName("data_quality");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<decimal>("Velocity")
                        .HasColumnType("numeric(10, 3)")
                        .HasColumnName("velocity");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "Timestamp")
                        .IsUnique()
                        .HasDatabaseName("idx_velocities_site_time");

                    b.ToTable("flow_velocities");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.InstantaneousFlow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<short>("DataQuality")
                        .HasColumnType("smallint")
                        .HasColumnName("data_quality");

                    b.Property<decimal>("FlowRate")
                        .HasColumnType("numeric(10, 3)")
                        .HasColumnName("flow_rate");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "Timestamp")
                        .IsUnique()
                        .HasDatabaseName("idx_flows_site_time");

                    b.ToTable("instantaneous_flows");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.InternalHumidity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DataQuality")
                        .HasColumnType("integer")
                        .HasColumnName("data_quality");

                    b.Property<decimal>("InternalHumidityValue")
                        .HasColumnType("numeric")
                        .HasColumnName("internalhumidity");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "Timestamp")
                        .IsUnique()
                        .HasDatabaseName("idx_internalhumiditys_site_time");

                    b.ToTable("internalhumiditys");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.InternalTemp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DataQuality")
                        .HasColumnType("integer")
                        .HasColumnName("data_quality");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(10, 3)")
                        .HasColumnName("internaltemp");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "Timestamp")
                        .IsUnique()
                        .HasDatabaseName("idx_internaltemps_site_time");

                    b.ToTable("internaltemps");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.LoginLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("LoginTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("login_time")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("login_logs");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.MotorWindingTemp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DataQuality")
                        .HasColumnType("integer")
                        .HasColumnName("data_quality");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(10, 3)")
                        .HasColumnName("motorwindingtemp");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "Timestamp")
                        .IsUnique()
                        .HasDatabaseName("idx_motorwindingtemps_site_time");

                    b.ToTable("motorwindingtemps");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.NetWeight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DataQuality")
                        .HasColumnType("integer")
                        .HasColumnName("data_quality");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(10, 3)")
                        .HasColumnName("netweight");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "Timestamp")
                        .IsUnique()
                        .HasDatabaseName("idx_netweights_site_time");

                    b.ToTable("netweights");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.OperationalParameters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AirQualityThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("air_quality_threshold");

                    b.Property<double?>("AlmFlowLow")
                        .HasColumnType("double precision")
                        .HasColumnName("alm_flow_low");

                    b.Property<double?>("AlmLevelDiff")
                        .HasColumnType("double precision")
                        .HasColumnName("alm_level_diff");

                    b.Property<double?>("AlmLevelDopplerHigh")
                        .HasColumnType("double precision")
                        .HasColumnName("alm_level_doppler_high");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("HartEn")
                        .HasColumnType("boolean")
                        .HasColumnName("hart_en");

                    b.Property<bool>("HeatingIsRunning")
                        .HasColumnType("boolean")
                        .HasColumnName("heating_is_running");

                    b.Property<int?>("HumidityMax")
                        .HasColumnType("integer")
                        .HasColumnName("humidity_max");

                    b.Property<int?>("HumidityMin")
                        .HasColumnType("integer")
                        .HasColumnName("humidity_min");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<double?>("MotorColiAlmTemp")
                        .HasColumnType("double precision")
                        .HasColumnName("motor_coli_alm_temp");

                    b.Property<double?>("MotorColiCoolStartTemp")
                        .HasColumnType("double precision")
                        .HasColumnName("motor_coli_cool_start_temp");

                    b.Property<double?>("MotorColiCoolStopTemp")
                        .HasColumnType("double precision")
                        .HasColumnName("motor_coli_cool_stop_temp");

                    b.Property<double?>("MotorColiHeatTemp")
                        .HasColumnType("double precision")
                        .HasColumnName("motor_coli_heat_temp");

                    b.Property<double?>("MotorColiStopTemp")
                        .HasColumnType("double precision")
                        .HasColumnName("motor_coli_stop_temp");

                    b.Property<int?>("NoiseThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("noise_threshold");

                    b.Property<double?>("Pressure")
                        .HasColumnType("double precision")
                        .HasColumnName("pressure");

                    b.Property<int?>("PumpRunTime")
                        .HasColumnType("integer")
                        .HasColumnName("pump_run_time");

                    b.Property<int?>("PumpStopTime")
                        .HasColumnType("integer")
                        .HasColumnName("pump_stop_time");

                    b.Property<double?>("SetAlarmNetWeight")
                        .HasColumnType("double precision")
                        .HasColumnName("set_alarm_net_weight");

                    b.Property<double?>("SetD")
                        .HasColumnType("double precision")
                        .HasColumnName("set_d");

                    b.Property<double?>("SetI")
                        .HasColumnType("double precision")
                        .HasColumnName("set_i");

                    b.Property<double?>("SetLiquidLevelDiff")
                        .HasColumnType("double precision")
                        .HasColumnName("set_liquid_level_diff");

                    b.Property<double?>("SetMVelocity")
                        .HasColumnType("double precision")
                        .HasColumnName("set_m_velocity");

                    b.Property<double?>("SetMaxTareWeight")
                        .HasColumnType("double precision")
                        .HasColumnName("set_max_tare_weight");

                    b.Property<double?>("SetP")
                        .HasColumnType("double precision")
                        .HasColumnName("set_p");

                    b.Property<double?>("SetVelocityAlm")
                        .HasColumnType("double precision")
                        .HasColumnName("set_velocity_alm");

                    b.Property<double?>("SetVelocityHighLimit")
                        .HasColumnType("double precision")
                        .HasColumnName("set_velocity_high_limit");

                    b.Property<double?>("SetVelocityLowLimit")
                        .HasColumnType("double precision")
                        .HasColumnName("set_velocity_low_limit");

                    b.Property<double?>("SetWarnWeight")
                        .HasColumnType("double precision")
                        .HasColumnName("set_warn_weight");

                    b.Property<double?>("TempMax")
                        .HasColumnType("double precision")
                        .HasColumnName("temp_max");

                    b.Property<double?>("TempMin")
                        .HasColumnType("double precision")
                        .HasColumnName("temp_min");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<double?>("VibrationThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("vibration_threshold");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("operational_parameters");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.SiteConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlarmEmailAddresses")
                        .HasColumnType("text")
                        .HasColumnName("alarm_email_addresses");

                    b.Property<bool>("AlarmEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("alarm_enabled");

                    b.Property<string>("AlarmPhoneNumbers")
                        .HasColumnType("text")
                        .HasColumnName("alarm_phone_numbers");

                    b.Property<string>("ConnectionStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("connection_status");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contact_person");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("GlobalCameraIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("global_camera_ip");

                    b.Property<string>("GlobalCameraPassword")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("global_camera_password");

                    b.Property<string>("GlobalCameraUsername")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("global_camera_username");

                    b.Property<string>("InternalCameraIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("internal_camera_ip");

                    b.Property<string>("InternalCameraPassword")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("internal_camera_password");

                    b.Property<string>("InternalCameraUsername")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("internal_camera_username");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean")
                        .HasColumnName("is_online");

                    b.Property<DateTime?>("LastHeartbeat")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat");

                    b.Property<bool>("OpcuaAnonymous")
                        .HasColumnType("boolean")
                        .HasColumnName("opcua_anonymous");

                    b.Property<string>("OpcuaEndpoint")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("opcua_endpoint");

                    b.Property<string>("OpcuaPassword")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("opcua_password");

                    b.Property<int>("OpcuaRequestTimeout")
                        .HasColumnType("integer")
                        .HasColumnName("opcua_request_timeout");

                    b.Property<string>("OpcuaSecurityMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("opcua_security_mode");

                    b.Property<string>("OpcuaSecurityPolicy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("opcua_security_policy");

                    b.Property<int>("OpcuaSessionTimeout")
                        .HasColumnType("integer")
                        .HasColumnName("opcua_session_timeout");

                    b.Property<string>("OpcuaUsername")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("opcua_username");

                    b.Property<string>("OperatingPressureMax")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("operating_pressure_max");

                    b.Property<string>("OperatingPressureMin")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("operating_pressure_min");

                    b.Property<int?>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("protocol");

                    b.Property<int>("PumpCount")
                        .HasColumnType("integer")
                        .HasColumnName("pump_count");

                    b.Property<string>("SiteCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("site_code");

                    b.Property<string>("SiteDescription")
                        .HasColumnType("text")
                        .HasColumnName("site_description");

                    b.Property<string>("SiteLocation")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("site_location");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("site_name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SiteCode")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("site_configs");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.Speed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DataQuality")
                        .HasColumnType("integer")
                        .HasColumnName("data_quality");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer")
                        .HasColumnName("site_id");

                    b.Property<decimal>("SpeedValue")
                        .HasColumnType("numeric")
                        .HasColumnName("speed");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "Timestamp")
                        .IsUnique()
                        .HasDatabaseName("idx_speeds_site_time");

                    b.ToTable("speeds");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.SystemConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("EmailAccount")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email_account");

                    b.Property<string>("EmailPassword")
                        .HasColumnType("text")
                        .HasColumnName("email_password");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PhoneAccessId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("phone_access_id");

                    b.Property<string>("PhoneAccessKey")
                        .HasColumnType("text")
                        .HasColumnName("phone_access_key");

                    b.Property<string>("PhoneAlarmAddress")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("phone_alarm_address");

                    b.Property<string>("SmsAccessId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sms_access_id");

                    b.Property<string>("SmsAccessKey")
                        .HasColumnType("text")
                        .HasColumnName("sms_access_key");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("integer")
                        .HasColumnName("smtp_port");

                    b.Property<string>("SmtpServer")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("smtp_server");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("system_configs");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.TelemetryMinute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("CabinetInnerTemperature")
                        .HasColumnType("double precision")
                        .HasColumnName("cabinet_inner_temperature");

                    b.Property<double?>("CabinetOuterHumidity")
                        .HasColumnType("double precision")
                        .HasColumnName("cabinet_outer_humidity");

                    b.Property<double?>("CabinetOuterTemperature")
                        .HasColumnType("double precision")
                        .HasColumnName("cabinet_outer_temperature");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<double?>("DownstreamLevel")
                        .HasColumnType("double precision")
                        .HasColumnName("downstream_level");

                    b.Property<double?>("ElectricCurrent")
                        .HasColumnType("double precision")
                        .HasColumnName("electric_current");

                    b.Property<double?>("FlowVelocity")
                        .HasColumnType("double precision")
                        .HasColumnName("flow_velocity");

                    b.Property<double?>("InstantaneousFlow")
                        .HasColumnType("double precision")
                        .HasColumnName("instantaneous_flow");

                    b.Property<double?>("NetWeight")
                        .HasColumnType("double precision")
                        .HasColumnName("net_weight");

                    b.Property<string>("SiteCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("site_code");

                    b.Property<double?>("Speed")
                        .HasColumnType("double precision")
                        .HasColumnName("speed");

                    b.Property<DateTime>("TsMinute")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ts_minute");

                    b.Property<double?>("UpstreamLevel")
                        .HasColumnType("double precision")
                        .HasColumnName("upstream_level");

                    b.Property<double?>("WaterTemperature")
                        .HasColumnType("double precision")
                        .HasColumnName("water_temperature");

                    b.Property<double?>("WindingTemperature")
                        .HasColumnType("double precision")
                        .HasColumnName("winding_temperature");

                    b.HasKey("Id");

                    b.HasIndex("SiteCode", "TsMinute")
                        .IsUnique()
                        .HasDatabaseName("uq_site_minute");

                    b.HasIndex(new[] { "SiteCode" }, "IX_telemetry_minute_SiteCode");

                    b.HasIndex(new[] { "TsMinute" }, "IX_telemetry_minute_TsMinute");

                    b.HasIndex(new[] { "SiteCode", "TsMinute" }, "ix_telemetry_minute_site_time");

                    b.ToTable("telemetry_minute");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.UpstreamWaterLevel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<short>("DataQuality")
                        .HasColumnType("smallint")
                        .HasColumnName("data_quality");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<decimal>("WaterLevel")
                        .HasColumnType("numeric(10, 3)")
                        .HasColumnName("water_level");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "Timestamp")
                        .IsUnique()
                        .HasDatabaseName("idx_upstream_levels_site_time");

                    b.ToTable("upstream_water_levels");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuditPermissions")
                        .HasColumnType("text")
                        .HasColumnName("audit_permissions");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("hashed_password");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("OperationPermissions")
                        .HasColumnType("text")
                        .HasColumnName("operation_permissions");

                    b.Property<int>("OperationTimeout")
                        .HasColumnType("integer")
                        .HasColumnName("operation_timeout");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<UserStatus>("Status")
                        .HasColumnType("userstatus")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<UserGroup>("UserGroup")
                        .HasColumnType("usergroup")
                        .HasColumnName("user_group");

                    b.Property<UserLevel>("UserLevel")
                        .HasColumnType("userlevel")
                        .HasColumnName("user_level");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.UserAlarmNotificationConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlarmName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("alarm_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("EmailAlarmEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("email_alarm_enabled");

                    b.Property<bool>("GlobalPhotoEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("global_photo_enabled");

                    b.Property<bool>("InternalPhotoEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("internal_photo_enabled");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<bool>("PhoneAlarmEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_alarm_enabled");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("scope");

                    b.Property<string>("ScopeTarget")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("scope_target");

                    b.Property<bool>("SmsAlarmEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("sms_alarm_enabled");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_alarm_notifications");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AlarmEmailEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("alarm_email_enabled");

                    b.Property<bool>("AlarmEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("alarm_enabled");

                    b.Property<bool>("AlarmSmsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("alarm_sms_enabled");

                    b.Property<bool>("AlarmSoundEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("alarm_sound_enabled");

                    b.Property<bool>("AutoErrorReset")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_error_reset");

                    b.Property<double>("BrushCurrentHighThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("brush_current_high_threshold");

                    b.Property<double>("BrushCurrentLowThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("brush_current_low_threshold");

                    b.Property<double>("BrushPowerHighThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("brush_power_high_threshold");

                    b.Property<double>("BrushPowerLowThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("brush_power_low_threshold");

                    b.Property<double>("BrushSpeedHighThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("brush_speed_high_threshold");

                    b.Property<double>("BrushSpeedLowThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("brush_speed_low_threshold");

                    b.Property<double>("BrushTempHighThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("brush_temp_high_threshold");

                    b.Property<double>("BrushTempLowThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("brush_temp_low_threshold");

                    b.Property<int>("ChartDataPoints")
                        .HasColumnType("integer")
                        .HasColumnName("chart_data_points");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CustomSettings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("custom_settings");

                    b.Property<int>("DataRefreshInterval")
                        .HasColumnType("integer")
                        .HasColumnName("data_refresh_interval");

                    b.Property<string>("DefaultSystemMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("default_system_mode");

                    b.Property<int>("ErrorCheckInterval")
                        .HasColumnType("integer")
                        .HasColumnName("error_check_interval");

                    b.Property<double>("HumidityHighThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("humidity_high_threshold");

                    b.Property<double>("HumidityLowThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("humidity_low_threshold");

                    b.Property<double>("LevelDiffHighThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("level_diff_high_threshold");

                    b.Property<double>("LevelDiffLowThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("level_diff_low_threshold");

                    b.Property<double>("LevelHighThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("level_high_threshold");

                    b.Property<double>("LevelLowThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("level_low_threshold");

                    b.Property<double>("MotorCurrentHighThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("motor_current_high_threshold");

                    b.Property<double>("MotorCurrentLowThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("motor_current_low_threshold");

                    b.Property<double>("MotorPowerHighThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("motor_power_high_threshold");

                    b.Property<double>("MotorPowerLowThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("motor_power_low_threshold");

                    b.Property<double>("MotorSpeedHighThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("motor_speed_high_threshold");

                    b.Property<double>("MotorSpeedLowThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("motor_speed_low_threshold");

                    b.Property<double>("MotorTorqueHighThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("motor_torque_high_threshold");

                    b.Property<double>("MotorTorqueLowThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("motor_torque_low_threshold");

                    b.Property<double>("MotorWindingTempHighThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("motor_winding_temp_high_threshold");

                    b.Property<double>("MotorWindingTempLowThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("motor_winding_temp_low_threshold");

                    b.Property<double>("ScaleWeightHighThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("scale_weight_high_threshold");

                    b.Property<double>("ScaleWeightLowThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("scale_weight_low_threshold");

                    b.Property<bool>("ShowAdvancedControls")
                        .HasColumnType("boolean")
                        .HasColumnName("show_advanced_controls");

                    b.Property<double>("TempHighThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("temp_high_threshold");

                    b.Property<double>("TempLowThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("temp_low_threshold");

                    b.Property<string>("UiLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ui_language");

                    b.Property<string>("UiTheme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ui_theme");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<double>("WaterTempHighThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("water_temp_high_threshold");

                    b.Property<double>("WaterTempLowThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("water_temp_low_threshold");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_settings");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.UserSite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool?>("IsOwner")
                        .HasColumnType("boolean")
                        .HasColumnName("is_owner");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer")
                        .HasColumnName("site_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.HasIndex("UserId", "SiteId")
                        .IsUnique()
                        .HasDatabaseName("uq_user_site");

                    b.ToTable("user_sites");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.WaterTemperature", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<short>("DataQuality")
                        .HasColumnType("smallint")
                        .HasColumnName("data_quality");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("numeric(10, 3)")
                        .HasColumnName("temperature");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "Timestamp")
                        .IsUnique()
                        .HasDatabaseName("idx_temps_site_time");

                    b.ToTable("water_temperatures");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.AlarmConfig", b =>
                {
                    b.HasOne("PumpRoomAutomationBackend.Models.Entities.SiteConfig", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.AlarmRecord", b =>
                {
                    b.HasOne("PumpRoomAutomationBackend.Models.Entities.SiteConfig", "Site")
                        .WithMany("AlarmRecords")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.Current", b =>
                {
                    b.HasOne("PumpRoomAutomationBackend.Models.Entities.SiteConfig", "SiteConfig")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiteConfig");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.DownstreamWaterLevel", b =>
                {
                    b.HasOne("PumpRoomAutomationBackend.Models.Entities.SiteConfig", "SiteConfig")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiteConfig");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.ExternalHumidity", b =>
                {
                    b.HasOne("PumpRoomAutomationBackend.Models.Entities.SiteConfig", "SiteConfig")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiteConfig");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.ExternalTemp", b =>
                {
                    b.HasOne("PumpRoomAutomationBackend.Models.Entities.SiteConfig", "SiteConfig")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiteConfig");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.FlowVelocity", b =>
                {
                    b.HasOne("PumpRoomAutomationBackend.Models.Entities.SiteConfig", "SiteConfig")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiteConfig");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.InstantaneousFlow", b =>
                {
                    b.HasOne("PumpRoomAutomationBackend.Models.Entities.SiteConfig", "SiteConfig")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiteConfig");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.InternalHumidity", b =>
                {
                    b.HasOne("PumpRoomAutomationBackend.Models.Entities.SiteConfig", "SiteConfig")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiteConfig");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.InternalTemp", b =>
                {
                    b.HasOne("PumpRoomAutomationBackend.Models.Entities.SiteConfig", "SiteConfig")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiteConfig");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.MotorWindingTemp", b =>
                {
                    b.HasOne("PumpRoomAutomationBackend.Models.Entities.SiteConfig", "SiteConfig")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiteConfig");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.NetWeight", b =>
                {
                    b.HasOne("PumpRoomAutomationBackend.Models.Entities.SiteConfig", "SiteConfig")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiteConfig");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.OperationalParameters", b =>
                {
                    b.HasOne("PumpRoomAutomationBackend.Models.Entities.User", "User")
                        .WithMany("OperationalParameters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.SiteConfig", b =>
                {
                    b.HasOne("PumpRoomAutomationBackend.Models.Entities.User", "User")
                        .WithMany("SiteConfigs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.Speed", b =>
                {
                    b.HasOne("PumpRoomAutomationBackend.Models.Entities.SiteConfig", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.SystemConfig", b =>
                {
                    b.HasOne("PumpRoomAutomationBackend.Models.Entities.User", "User")
                        .WithMany("SystemConfigs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.UpstreamWaterLevel", b =>
                {
                    b.HasOne("PumpRoomAutomationBackend.Models.Entities.SiteConfig", "SiteConfig")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiteConfig");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.UserAlarmNotificationConfig", b =>
                {
                    b.HasOne("PumpRoomAutomationBackend.Models.Entities.User", "User")
                        .WithMany("AlarmConfigs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.UserSettings", b =>
                {
                    b.HasOne("PumpRoomAutomationBackend.Models.Entities.User", "User")
                        .WithOne("Settings")
                        .HasForeignKey("PumpRoomAutomationBackend.Models.Entities.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.UserSite", b =>
                {
                    b.HasOne("PumpRoomAutomationBackend.Models.Entities.SiteConfig", "SiteConfig")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PumpRoomAutomationBackend.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiteConfig");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.WaterTemperature", b =>
                {
                    b.HasOne("PumpRoomAutomationBackend.Models.Entities.SiteConfig", "SiteConfig")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SiteConfig");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.SiteConfig", b =>
                {
                    b.Navigation("AlarmRecords");
                });

            modelBuilder.Entity("PumpRoomAutomationBackend.Models.Entities.User", b =>
                {
                    b.Navigation("AlarmConfigs");

                    b.Navigation("OperationalParameters");

                    b.Navigation("Settings");

                    b.Navigation("SiteConfigs");

                    b.Navigation("SystemConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
